
debug: true

server:
  port: 8090


#springboot??
spring:
  # ???
  devtools:
    restart:
      enabled: true #???????

  # ?????
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/security?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: wangle2018


# mybatis-plus??
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  auto-mapping-behavior: full
#    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  mapper-locations: classpath:/com/example/security/sys/xml/*Mapper.xml
#    global-config:
#      db-config:
#        logic-delete-field: deleted
#        logic-not-delete-value: 1
#        logic-delete-value: 0

      #  type-aliases-package: com.example.system.model


    #??oss??
    #alioss:
    #  endpoint: oss-cn-beijing.aliyuncs.com
    #  accessKeyId: LTAI5tL4oSkKN7MMwbzhv7i2
    #  accessKeySecret: w0zCxoXbX232d1CBy1MPEDmmUPIG7D
    #  bucketName: xinguan-study
    #

